feat: add app dynamics provide
keephq/keep pull request #1108
Opened 2024-04-16 10:06 UTC by 35C4n0r

- used appdynamics REST API to install webhooks, add HTTP Request Actions and add action to policies.

CLoses: #1089 
/claim #1089

Closes # 

## 📑 Description

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

2024-04-16 11:34 UTC, talboren commented on keep/providers/appdynamics_provider/appdynamics_provider.py
> +            severity=AppdynamicsProvider.SEVERITIES_MAP.get(event['severity']),
Did you test this? it'll fail because you pass severity twice (**event and severity=)

2024-04-16 11:35 UTC, talboren commented on keep/providers/appdynamics_provider/appdynamics_provider.py
> +            authenticated = False
Better error message? perhaps the response.json when authentication failed?

2024-04-16 14:32 UTC, talboren commented on keep/providers/appdynamics_provider/appdynamics_provider.py
> +        template["path"] = keep_api_path
template is a list, this doesn't seem to work, right?

2024-04-16 14:33 UTC, talboren requested changes
@35C4n0r I would very much appreciate if you can attach a screenshot (short video?) of a full cycle where you connect AppDynamics, install webhook and get an alert! 🙏🏼

2024-04-16 19:55 UTC, 35C4n0r commented
> @35C4n0r I would very much appreciate if you can attach a screenshot (short video?) of a full cycle where you connect AppDynamics, install webhook and get an alert! 🙏🏼

![WhatsApp Image 2024-04-17 at 00 44 09_d6679d3d](https://github.com/keephq/keep/assets/70096901/fe891f11-09fb-41fc-8439-9e3794e1b46e)

2024-04-17 06:53 UTC, shahargl commented on keep/providers/appdynamics_provider/appdynamics_provider.py
> +logger = logging.getLogger(__name__)
remove `logger` from here and use `self.logger` in the class

2024-04-17 06:55 UTC, shahargl commented
@35C4n0r please add the logo to readme.md also

left few comments, lets merge it today

2024-04-17 06:58 UTC, talboren commented
> > @35C4n0r I would very much appreciate if you can attach a screenshot (short video?) of a full cycle where you connect AppDynamics, install webhook and get an alert! 🙏🏼
> 
> ![WhatsApp Image 2024-04-17 at 00 44 09_d6679d3d](https://private-user-images.githubusercontent.com/70096901/322980853-fe891f11-09fb-41fc-8439-9e3794e1b46e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzczNTQsIm5iZiI6MTcxMzMzNzA1NCwicGF0aCI6Ii83MDA5NjkwMS8zMjI5ODA4NTMtZmU4OTFmMTEtMDlmYi00MWZjLTg0MzktOWUzNzk0ZTFiNDZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA2NTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNmQzMWYzOTgzNTg2Y2I4ODlhYmJhYTAwOGQ4MjU0ODU3ZjdhYmY0MzQ0MDY5OWFhZWNlMTRiODM1YzRmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y4blJ7NdtI01FZAwFTkWg7Z2_e5-MDScRpHoYm4U6Os)

@35C4n0r thanks! can we also see some incoming alerts? 🙏🏼

2024-04-17 07:16 UTC, 35C4n0r commented
> > > @35C4n0r I would very much appreciate if you can attach a screenshot (short video?) of a full cycle where you connect AppDynamics, install webhook and get an alert! 🙏🏼
> > 
> > ![WhatsApp Image 2024-04-17 at 00 44 09_d6679d3d](https://private-user-images.githubusercontent.com/70096901/322980853-fe891f11-09fb-41fc-8439-9e3794e1b46e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzczNTQsIm5iZiI6MTcxMzMzNzA1NCwicGF0aCI6Ii83MDA5NjkwMS8zMjI5ODA4NTMtZmU4OTFmMTEtMDlmYi00MWZjLTg0MzktOWUzNzk0ZTFiNDZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA2NTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNmQzMWYzOTgzNTg2Y2I4ODlhYmJhYTAwOGQ4MjU0ODU3ZjdhYmY0MzQ0MDY5OWFhZWNlMTRiODM1YzRmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y4blJ7NdtI01FZAwFTkWg7Z2_e5-MDScRpHoYm4U6Os)
> 
> @35C4n0r thanks! can we also see some incoming alerts? 🙏🏼 

.... I did receive alerts from PagerDuty, how did that happen I'm on localhost and it was on a different server, how do I do the same for AppDynamics?
I tested out the alerts with a simple webhook tester website.

2024-04-17 09:46 UTC, 35C4n0r commented
![image](https://github.com/keephq/keep/assets/70096901/23cc6a1f-595e-4aef-8dd9-38cecd95ecc5)

2024-04-17 09:48 UTC, 35C4n0r commented
![image](https://github.com/keephq/keep/assets/70096901/6eb3f2ba-62b3-4a36-a34b-53463c295442)

2024-04-17 14:44 UTC, shahargl approved these changes
lgtm

2024-04-17 14:44 UTC, shahargl commented on keep/providers/appdynamics_provider/appdynamics_provider.py
> +        # url = https://test.atlassian.net/rest/api/2/issue/createmeta?projectKeys=key1
?

2024-04-17 14:44 UTC, shahargl commented on keep/providers/appdynamics_provider/appdynamics_provider.py
> +        # url = https://test.atlassian.net/rest/api/2/issue/createmeta?projectKeys=key1
fix this - atlassian is not related

2024-04-17 14:45 UTC, shahargl requested changes
see comments

2024-04-17 14:52 UTC, 35C4n0r commented on keep/providers/appdynamics_provider/appdynamics_provider.py
> +    alerts = provider.setup_webhook("test", "http://localhost:8000", "1234", True)
XD I just copied the template from grafana, and edited it. What should I replace it with?

2024-04-17 14:54 UTC, 35C4n0r commented on keep/providers/appdynamics_provider/httpactiontemplate.json
> +[
Comment added in l#182

2024-04-17 15:06 UTC, merged