Support for mongodb without database and binary data
keephq/keep pull request #1236
Opened 2024-06-13 16:09 UTC by HNitzanH

Closes # 

## 📑 Description

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

2024-06-13 16:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/keephq/keep?pullRequest=1236) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/keephq/keep?pullRequest=1236) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/keephq/keep?pullRequest=1236) it.</sub>

2024-06-16 22:37 UTC, talboren commented on keep/providers/mongodb_provider/mongodb_provider.py
> +            raise Exception("Trying to query a database, but none was given in the provider, please update the provider to contain database name")
```suggestion
            raise Exception("Trying to query a database, but none was given in the provider, please update the provider to include a database name")
```

2024-06-17 07:23 UTC, shahargl commented on keep/api/core/db.py
> +        workflow_results = json.dumps(workflow_results, default=str)
its not how to do it, you can do it on the model itself with sqlmodel/sqlalchemy

2024-06-17 07:23 UTC, shahargl requested changes

2024-06-17 07:23 UTC, shahargl commented on keep/api/routes/workflows.py
> +    workflow_execution.results = json.loads(workflow_execution.results)
its not how to do it, you can do it on the model itself with sqlmodel/sqlalchemy

2024-06-18 11:16 UTC, closed without merging