Fix/extraction no such column updated at
keephq/keep pull request #1284
Opened 2024-06-25 10:23 UTC by VladimirFilonov

## 📑 Description

While creating extraction rule it was throwing SQL error:

```json
{
    "message": "An internal server error occurred.",
    "trace_id": "x",
    "error_msg": "(sqlite3.OperationalError) no such column: updated_at\n[SQL: INSERT INTO extractionrule (tenant_id, priority, name, description, created_by, created_at, updated_by, updated_at, disabled, pre, condition, attribute, regex) VALUES (?, ?, ?, ?, ?, ?, ?, updated_at, ?, ?, ?, ?, ?) /*db_driver='pysqlite',db_framework='sqlalchemy%%3A0.41b0',traceparent='x'*/]\n[parameters: ('keep', 0, 'asd', 'asd', 'admin@keephq', '2024-04-20 12:30:39.005900', None, 0, 0, '', 'asd', '(?P<groupname>)')]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)"
}
```

The problem here was in using sa.Column instance directly, without wrapping it with Field. As a result, when no value for updated_at was provided during the SQL query string generation, the engine treated this Column as an expression. Like if we were doing INSERT INTO SELECT. 

`VALUES (?, ?, ?, ?, ?, ?, ?, updated_at, ?, ?, ?, ?, ?)` <- SQL engine is trying to find column `updated_at` in our INSERT statement (not in target table), and of course can't. That's why we have `no such column: updated_at` - this is not about the field in the table but the virtual field in the request.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

## ℹ Additional Information

1. I extracted them to a separate module to re-use test_app and client, created in test_auth.
2. The original goal of using Column for update_at was to make this field automatically updated. But I see some inconsistency here with [MappingRule.last_updated_at](https://github.com/keephq/keep/blob/main/keep/api/models/db/mapping.py#L29). Sould we align then to have the same behavior?

2024-06-25 10:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/keephq/keep?pullRequest=1284) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/keephq/keep?pullRequest=1284) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/keephq/keep?pullRequest=1284) it.</sub>

2024-06-30 14:16 UTC, shahargl commented
@VladimirFilonov ruff fails because of redundant import datetime (now when its not being used), can you remove it so e2e tests will run?

2024-06-30 14:17 UTC, shahargl requested changes
see comment

2024-07-01 17:23 UTC, VladimirFilonov commented
@shahargl Done, please check

2024-07-02 07:54 UTC, shahargl approved these changes
lgtm

2024-07-02 07:54 UTC, merged