fix: Error handling in UI is broken (ErrorComponent and ErrorBoundary) #
keephq/keep pull request #1290
Opened 2024-06-26 02:31 UTC by TakshPanchal

Closes #465 

## 📑 Description
Changed the order of error checking and added error boundary for `/provider`

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information
Need guidance from @shahargl regarding how exactly the error should display.

2024-06-26 02:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/keephq/keep?pullRequest=1290) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/keephq/keep?pullRequest=1290) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/keephq/keep?pullRequest=1290) it.</sub>

2024-06-26 09:22 UTC, shahargl commented
@TakshPanchal 

is is written that
> Error should be presented beautifully with all the context that is possible and a clear CTA should be displayed (e.g. "Try Again")

meaning the task is mainly around:
1. Make sure that when error happens show the error template
2. Create a beautiful error template with context and CTA

2024-06-26 10:34 UTC, talboren requested changes
Please see @shahargl's comment

2024-06-30 13:49 UTC, shahargl commented
closing since no activity, feel free to reopen when ready

2024-06-30 13:49 UTC, closed without merging