feat: API endpoint to see how many alerts a provider has sent
keephq/keep pull request #1480
Opened 2024-07-28 03:02 UTC by 35C4n0r

- add service function in api/core/db.py
- add endpoint in api/routes/providers.py

Closes #1249 
/claim #1249

## 📑 Description

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

2024-07-28 07:23 UTC, talboren commented on keep/api/routes/providers.py
> +        )
raise HTTPException instead

2024-07-28 07:24 UTC, talboren commented on keep/api/routes/providers.py
> +            )
lets define a model for it

2024-07-28 07:24 UTC, talboren commented on keep/api/core/db.py
> +):
add documentation please

2024-07-28 07:24 UTC, talboren commented on keep/api/routes/providers.py
> +            )
(e.g., ProviderAlertsCountDto)

2024-07-28 07:24 UTC, talboren requested changes
some small changes

2024-07-28 07:24 UTC, talboren commented
@35C4n0r thank you for the contribution! left some small comments, can you please take a look at them?

2024-07-28 10:08 UTC, 35C4n0r commented
Hey @talboren, thanks for the review. I've made the needed changes.

2024-07-29 06:51 UTC, talboren commented on keep/api/routes/providers.py
> +    )
JSONResponse is redundant

2024-07-29 06:52 UTC, talboren commented on keep/api/models/provider.py
> +    tenant_id: str
I meant to use this for the response model not for the request model 😅

2024-07-29 06:52 UTC, talboren commented on keep/api/core/db.py
> +from keep.api.models.provider import ProviderAlertsCountDTO
better not import dtos in here, return the .count() number and construct the response in the route itself

2024-07-29 06:52 UTC, talboren requested changes
A few more changes 🙏🏼

2024-07-30 11:58 UTC, talboren approved these changes
LGTM

2024-07-30 12:22 UTC, merged