[👨🏻‍💻 Internal]: Using standard OTLP env convention on backend service
keephq/keep pull request #1973
Opened 2024-09-19 13:03 UTC by vr-varad

Closes #1817

## 📑 Description
Using standard OTLP env convention on backend service

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

2024-09-19 13:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/keephq/keep?pullRequest=1973) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/keephq/keep?pullRequest=1973) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/keephq/keep?pullRequest=1973) it.</sub>

2024-09-19 13:59 UTC, vr-varad commented
@talboren I have made the req changes could  u please review it whenever u are free?

2024-09-20 08:13 UTC, talboren commented on keep/api/observability.py
> +    otlp_metrics_endpoint = os.environ.get("OTEL_EXPORTER_OTLP_METRICS_ENDPOINT", None)
@vr-varad for the sake of backwards compatibility (assuming that some already use that), can we have default values first taken from the old env variables? see example in the next comment

2024-09-20 08:14 UTC, talboren commented on keep/api/observability.py
> +    service_name = os.environ.get("OTEL_SERVICE_NAME", "keep-api")
```suggestion
    service_name = os.environ.get("OTEL_SERVICE_NAME", os.environ.get("SERVICE_NAME", "keep-api"))
```

2024-09-20 08:14 UTC, talboren commented on keep/api/observability.py
> +            raise ValueError(f"Unsupported protocol: {parsed_url.scheme}")
move function outside

2024-09-20 08:15 UTC, talboren requested changes
2 small comments and we're ready to go!

2024-09-20 08:15 UTC, talboren commented
@ErezLevip FYI

2024-09-20 09:44 UTC, vr-varad commented
@talboren Done!!

2024-09-20 10:03 UTC, talboren approved these changes
LGTM, just need you to sign the CLA :)

2024-09-20 10:15 UTC, vr-varad commented
Done @talboren

2024-09-20 13:16 UTC, merged