fix: refactor the workflow execution component to reduce repaint/rend…
keephq/keep pull request #2211
Opened 2024-10-15 22:55 UTC by rajeshj11

…er the entire page when filters were applied and some minor style changes

Closes #2025

## 📑 Description

 refactor the workflow execution component to reduce repaint/re-rendering of entire page

## ✅ Checks

- [X] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [X] All the tests have passed

## ℹ Additional Information

2024-10-16 07:30 UTC, rajeshj11 commented
@shahargl @talboren please review

2024-10-22 07:15 UTC, rajeshj11 commented
@Kiryous can you please review?

2024-10-30 13:31 UTC, Kiryous requested changes
Hey Rajesh, thank you for your contribution! I left a few comments, please consider fixing them. Sorry for a delayed response.

2024-10-30 13:31 UTC, Kiryous commented on keep-ui/app/workflows/[workflow_id]/executions.tsx
> +  const apiUrl = getApiURL();
```suggestion
  const apiUrl = useApiUrl();
```
Now you need to use this client hook to get API url. Please import it.

2024-10-30 13:31 UTC, Kiryous commented on keep/api/routes/workflows.py
> +@router.get("/{workflow_id}/data", description="Get workflow by ID")
```suggestion
@router.get("/{workflow_id}", description="Get workflow by ID")
```

Let's use the route "/{workflow_id}" for general info about workflow and change current "/{workflow_id}" to "/{workflow_id}/runs"

2024-10-30 13:31 UTC, Kiryous commented on keep-ui/app/workflows/[workflow_id]/executions.tsx
> +const OverViewContent = ({ workflow_id }: { workflow_id: string }) => {
Let's rename this component and move it to its own file, `keep-ui/app/workflows/[workflow_id]/ui/WorkflowOverview.tsx
```suggestion
const WorkflowOverview = ({ workflow_id }: { workflow_id: string }) => {
```
`

2024-10-30 13:31 UTC, Kiryous commented on keep/api/routes/workflows.py
> +    except Exception as e:
Do we know any specific exceptions to expect here?

2024-10-30 13:31 UTC, Kiryous commented on keep-ui/app/workflows/builder/builder-modal.tsx
> +  hideClose,
Let's use cleaner name 
```suggestion
  hideCloseButton,
```

2024-10-31 16:59 UTC, Kiryous commented on keep/api/routes/workflows.py
> +@router.get("/{workflow_id}/logs", description="Get workflow executions by ID")
No, it won't conflict, because the route "/{workflow_id}/runs" would be resolved earlier. Please change.

2024-10-31 18:24 UTC, Kiryous approved these changes
LGTM! Thanks for the contribution, Rajesh!

2024-10-31 18:46 UTC, merged