[Feature] Add support for aws secret manager
keephq/keep pull request #2222
Opened 2024-10-17 05:41 UTC by HarshitVashisht11

Closes #2204

## 📑 Description

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

2024-10-17 05:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/keephq/keep?pullRequest=2222) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/keephq/keep?pullRequest=2222) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/keephq/keep?pullRequest=2222) it.</sub>

2024-10-17 08:44 UTC, talboren requested changes
Thank you for this! Can you please update https://github.com/keephq/keep/blob/446141d18bf436f370912a03037b253123acdf91/keep/secretmanager/secretmanagerfactory.py? I'll test that this works over AWS.

2024-10-17 13:08 UTC, shahargl commented on keep/secretmanager/awssecretmanager.py
> +                    raise e
except also a broad exception (not only client error) and add log

2024-10-17 13:10 UTC, shahargl commented
hey! thanks for the contribution.

@HarshitVashisht11 please update docs - https://docs.keephq.dev/deployment/secret-manager

2024-10-18 06:17 UTC, talboren approved these changes
LGTM!

2024-10-18 06:22 UTC, merged

2024-10-18 06:30 UTC, HarshitVashisht11 commented
Thank you , can you please add a `hacktoberfest-accepted` label