Fix workflow id and name usage
keephq/keep pull request #2685
Opened 2024-11-28 07:56 UTC by vishwamartur

Related to #1885

Update workflow parsing to use `id` as id and `name` as name, generate different UUID if `id` is not provided, and add validation for configuration errors.

* **keep/parser/parser.py**
  - Update `_get_workflow_id` to use `workflow.get("id")` for id and `workflow.get("name")` for name.
  - Add logic to generate a different UUID if `workflow.get("id")` is not provided.
  - Update `_parse_workflow` to use `workflow.get("name")` for name.

* **keep/api/models/db/workflow.py**
  - Add a new field `invalid` to mark workflows with configuration errors.
  - Update the `Workflow` class to include the `invalid` field.

* **keep/api/routes/workflows.py**
  - Update `create_workflow` and `create_workflow_from_body` to generate a different UUID if `workflow.get("id")` is not provided.
  - Add validation logic to mark workflows with configuration errors as `invalid`.

* **tests/test_parser.py**
  - Add test cases to verify that a different UUID is generated if `workflow.get("id")` is not provided.
  - Add test cases to verify that workflows with configuration errors are marked as `invalid`.

2024-11-28 07:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/keephq/keep?pullRequest=2685) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/keephq/keep?pullRequest=2685) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/keephq/keep?pullRequest=2685) it.</sub>

2024-12-16 07:37 UTC, Matvey-Kuk requested changes

2024-12-16 07:37 UTC, Matvey-Kuk commented on keep/api/models/db/workflow.py
> +    invalid: bool = Field(default=False)  # P22f5
This change should be reflected in a migration. Also what's P22f5? :)

2024-12-16 07:37 UTC, Matvey-Kuk commented on keep/api/routes/workflows.py
> +            workflow["id"] = str(uuid.uuid4())
May be added to __get_workflow_raw_data?

2024-12-29 18:37 UTC, closed without merging

2024-12-29 18:37 UTC, talboren commented
This is open for more than a month. Closing for now, please re-open if it's relevant
cc: @vishwamartur @Matvey-Kuk