added gitlab pipelines provider
keephq/keep pull request #353
Opened 2023-09-23 12:45 UTC by melsonic

Closes #326

### Description
Added Gitlab Pipelines Provider to interact with the Gitlab Pipelines API.

/claim #326

2023-09-25 16:56 UTC, talboren commented
Thanks! Will review it ASAP :)

Can you take a look at https://docs.keephq.dev/ and add the provider documentation? (How to get the webhook url, etc.)

Please also add a PNG of GitLab pipelines icon to keep-up/public/icons 🙏🏼

2023-09-26 04:44 UTC, melsonic commented
> Thanks! Will review it ASAP :)
> 
> Can you take a look at https://docs.keephq.dev/ and add the provider documentation? (How to get the webhook url, etc.)
> 
> Please also add a PNG of GitLab pipelines icon to keep-up/public/icons 🙏🏼

Sure, I will update the documentation and the icon, and if the review recommends some change I will do that altogether.

2023-09-26 05:31 UTC, shahargl requested changes
lgtm just few small things - 
1. add the svg
2. add docs (under docs/) how to use/get the token

2023-09-26 10:35 UTC, melsonic commented
> lgtm just few small things -
> 
> 1. add the svg
> 2. add docs (under docs/) how to use/get the token

Sure, I will add these changes ASAP :+1:

2023-09-26 12:05 UTC, melsonic commented
> lgtm just few small things -
> 
> 1. add the svg
> 2. add docs (under docs/) how to use/get the token

Hi @shahargl before pushing a commit, please clarify these two points
1. Is this the correct logo for Gitlab Pipelines? 
![IMG_20230926_173331](https://github.com/keephq/keep/assets/88551650/71fee609-05f0-49c8-9d5f-6a4908ca3670)
2. Is there any preferable format for the provider documentation?

2023-09-27 10:34 UTC, melsonic commented
please review the changes @shahargl

2023-09-27 12:39 UTC, shahargl approved these changes
lgtm

2023-09-27 12:43 UTC, shahargl commented on keep/providers/gitlabpipelines_provider/gitlabpipelines_provider.py
> +class GitlabPipelinesProvider(BaseProvider):
This should be GitlabpipelinesProvider

2023-09-27 12:44 UTC, shahargl requested changes
change the class name to GitlabpipelinesProvider so tests will pass

2023-09-27 14:09 UTC, melsonic commented on keep/providers/gitlabpipelines_provider/gitlabpipelines_provider.py
> +class GitlabPipelinesProvider(BaseProvider):
sure

2023-09-28 12:03 UTC, merged

2023-09-28 12:50 UTC, melsonic commented
Hi, @shahargl how can I claim this bounty? it is not showing in the dashboard