feat: twilio provider
keephq/keep pull request #454
Opened 2023-11-06 13:57 UTC by sc231997

Closes #446 

## 📑 Description
Twilio Provider added
Documentation added

## ✅ Checks

- [x ] My pull request adheres to the code style of this project
- [ x] My code requires changes to the documentation
- [ x] I have updated the documentation as required
- [ x] All the tests have passed

## ℹ Additional Information

2023-11-06 14:05 UTC, shahargl commented
hey @sc231997, nice work! Can you please add the scope validation? 

You can look at `jira_provider`/`grafana_provider` for example.
You basically need two things:
1. Expose `PROVIDER_SCOPES` which is list of `ProviderScope`
2. implement the `validate_scopes` function

2023-11-06 14:07 UTC, shahargl requested changes
hey @sc231997, nice work! Can you please add the scope validation?

You can look at jira_provider/grafana_provider for example.
You basically need two things:

Expose PROVIDER_SCOPES which is list of ProviderScope
implement the validate_scopes function
Also please add twillo-icon.png under keep-ui/public/icons

2023-11-06 14:12 UTC, sc231997 commented
> hey @sc231997, nice work! Can you please add the scope validation?
> 
> You can look at `jira_provider`/`grafana_provider` for example. You basically need two things:
> 
> 1. Expose `PROVIDER_SCOPES` which is list of `ProviderScope`
> 2. implement the `validate_scopes` function

Hi @shahargl 
Thanks!
I have a question related to `scopes`. Does `scope` here indicate weather the API token can send SMS or not? If yes, can you point me to Twilio docs, cannot find any related to that.

2023-11-06 14:43 UTC, shahargl commented
@sc231997 basically we need any indication that the api token (or any other credentials) is ok.

I think the easiest way is to implement sending a message in validate_scopes.

So the scope should be something like "Send message" (message.send)
and validate scopes should be:
```python
...
try:
   # 15005550006 is a magic number according to https://www.twilio.com/docs/messaging/tutorials/automate-testing
   message = client.messages.create(body='All in the game, yo',  from_='+5571981265145', to='15005550006')
   scopes['message.read'] = True
except Exception as e:
    # validate the exception 
    if "authentication failed" in str(e)
        scopes['message.send'] = "Failed to send message - authentication failed"
    else:
      ...
      
```

2023-11-07 08:26 UTC, shahargl commented on keep/providers/twilio_provider/twilio_provider.py
> +                    validated_scopes[scope.name] = False
```suggestion
                    validated_scopes[scope.name] = f"Failed to send a test SMS - {str(e)}"
```

2023-11-07 08:26 UTC, shahargl commented on keep/providers/twilio_provider/twilio_provider.py
> +                    # from: 15005550006 is a magic number according to https://www.twilio.com/docs/messaging/tutorials/automate-testing
add debug log

2023-11-07 08:27 UTC, shahargl commented on keep/providers/twilio_provider/twilio_provider.py
> +                    validated_scopes[scope.name] = True
add debug log after ("test sms sent successfully")

2023-11-07 08:28 UTC, shahargl requested changes
minor changes

2023-11-07 09:22 UTC, shahargl approved these changes
lgtm

2023-11-07 09:25 UTC, merged