feature : api key improvement
keephq/keep pull request #716
Opened 2024-01-16 10:28 UTC by Min2who

Closes #708 

## 📑 Description
This is work in progress

2024-01-16 10:29 UTC, Min2who commented
can yu reviwed the backend changes 
cc @shahargl

2024-01-17 13:56 UTC, shahargl commented on keep/api/models/apikey.py
> +    created_at: str
Add also:
1. role
2. last used (we will update when the api key is used)

2024-01-17 13:56 UTC, shahargl commented on keep/api/models/db/apikey.py
> +class APIKey(SQLModel, table=True):
you don't need a new table. there is already tenantapikey, just use it.

2024-01-17 17:08 UTC, shahargl requested changes
see comments

2024-01-17 17:27 UTC, Min2who commented
> see comments

@shahargl added the changes

2024-01-20 09:09 UTC, Min2who commented
> Once you’ll have the UI I’ll be able to test it @Min2who

@shahargl really sorry for late reply . you can open the bounty to other i have some college work that pop up and will be occupied with it upto 3 weeks

2024-01-21 07:51 UTC, closed without merging