Main
keephq/keep pull request #904
Opened 2024-03-06 08:37 UTC by mohanish2504

/claim #640
/close #640

2024-03-07 05:23 UTC, 35C4n0r commented
@mohanish2504 kindly add /split @35C4n0r  to the PR body

![Screenshot_2024-03-07-10-52-29-84_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://github.com/keephq/keep/assets/70096901/5218e070-8f47-4460-99ee-2a1e579a59d7)

2024-03-07 05:26 UTC, 35C4n0r commented
@shahargl @talboren PR is ready fr review.

2024-03-07 06:30 UTC, mohanish2504 commented
/split @35C4n0r

2024-03-07 17:53 UTC, talboren commented
@mohanish2504 @35C4n0r please add some UI images to the PR 🙏🏼

2024-03-07 18:03 UTC, 35C4n0r commented
![image](https://github.com/keephq/keep/assets/70096901/79d3ad8f-efb2-4f2c-9fcb-5c5561813e3e)
@talboren

2024-03-07 18:05 UTC, mohanish2504 commented
> ![image](https://private-user-images.githubusercontent.com/70096901/310989741-79d3ad8f-efb2-4f2c-9fcb-5c5561813e3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzQ5NjYsIm5iZiI6MTcwOTgzNDY2NiwicGF0aCI6Ii83MDA5NjkwMS8zMTA5ODk3NDEtNzlkM2FkOGYtZWZiMi00ZjJjLTlmY2ItNWM1NTYxODEzZTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE4MDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4Y2U0OGNlNzYxN2ZlZGRkNjAwMTg5MzIyYWU2OTIxMzljZTZkYjgyN2MzYmQ3MTg2OWQyZTBhNGQwYjFhNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hypI6jkQZ3JSsuPy5PNTYJTC9tRWXxMBrKzZwJ3mqcs) @talboren

@35C4n0r lets match buttons with UI theme?

2024-03-07 18:29 UTC, 35C4n0r commented
@talboren @mohanish2504 done
![image](https://github.com/keephq/keep/assets/70096901/51dea2d2-e2c9-44ac-b320-649ca5444f08)

2024-03-07 18:34 UTC, talboren commented
Modal looks too big. Please decrease its size please

2024-03-07 18:45 UTC, 35C4n0r commented
@talboren 
Reduced the size + Matching theme
![image](https://github.com/keephq/keep/assets/70096901/3b1569d1-8b9b-4bc4-810a-e62e9026b95f)

2024-03-07 23:36 UTC, talboren requested changes
Some changes required 🙏🏼

2024-03-07 23:36 UTC, talboren commented on keep-ui/app/alerts/alert-presets.tsx
> +        onClose={() => {}}
```suggestion
        onClose={() => setIsModalOpen(false)}
```

2024-03-07 23:36 UTC, talboren commented on keep-ui/app/alerts/alert-presets.tsx
> +    // console.log("HELLO WORLD");
Remove comments

2024-03-07 23:36 UTC, talboren commented on keep-ui/app/alerts/alert-presets.tsx
> +import AlertTableCheckbox from "./alert-table-checkbox";
What for?

2024-03-07 23:36 UTC, talboren commented on keep/api/models/db/preset.py
> +    # if created_by is not null then it means this preset is only for this user
Then why have` is_private` as well?

2024-03-08 02:55 UTC, 35C4n0r commented on keep/api/models/db/preset.py
> +    # if created_by is not null then it means this preset is only for this user
@mohanish2504

2024-03-08 02:56 UTC, 35C4n0r commented on keep-ui/app/alerts/alert-presets.tsx
> +    // console.log("HELLO WORLD");
done

2024-03-08 02:57 UTC, 35C4n0r commented on keep-ui/app/alerts/alert-presets.tsx
> +import AlertTableCheckbox from "./alert-table-checkbox";
resolved

2024-03-08 02:57 UTC, 35C4n0r commented on keep-ui/app/alerts/alert-presets.tsx
> +        onClose={() => {}}
resolved

2024-03-08 11:00 UTC, talboren commented on keep/api/routes/preset.py
> +    # only global presets
This is both global and private, right?

2024-03-10 13:16 UTC, talboren requested changes
1 more thing that needs to be done and this can be approved and merged!

In `db.py` search for the `try_create_single_tenant` function and update it to also try and "migrate" the presets table. This is a bit ugly but this is what we got in the meanwhile until we implement a different mechanism.
Look at the example of `TenantApiKey` migration and apply the same for the 2 newly added columns of `Preset`

2024-03-10 13:17 UTC, mohanish2504 commented
Yep I am aware of it

2024-03-10 15:09 UTC, talboren requested changes
1 more thing to go 🚀

2024-03-10 15:09 UTC, talboren commented on keep/api/core/db.py
> +            session.exec("ALTER TABLE preset ADD COLUMN created_by TEXT DEFAULT '';")
I'm getting this: `Error Code: 1101. BLOB, TEXT, GEOMETRY or JSON column 'created_by' can't have a default value`

2024-03-10 15:10 UTC, talboren commented on keep/api/core/db.py
> +            session.exec("ALTER TABLE preset ADD COLUMN created_by TEXT DEFAULT '';")
```suggestion
            session.exec("ALTER TABLE preset ADD COLUMN created_by VARCHAR(1024) DEFAULT '';")
```

2024-03-10 15:11 UTC, talboren approved these changes
LGTM

2024-03-10 15:13 UTC, merged

2024-03-10 15:26 UTC, talboren commented
@mohanish2504 @35C4n0r bounty awarded, let me know you got it :) Thanks for the contribution!