feat: incident manager provider.
keephq/keep pull request #967
Opened 2024-03-16 02:13 UTC by mohanish2504

/closes #804
/claim #804

2024-03-17 13:08 UTC, shahargl requested changes

2024-03-17 13:08 UTC, shahargl commented on keep/providers/incident_manager_provider/incident_manager_provider.py
> +"""
Add:
1. Documentation on how to connect with the provider
2. Provider icon

2024-03-19 13:54 UTC, mohanish2504 commented
@shahargl @talboren sorry for dealyed response will add the remaing part

2024-04-03 10:02 UTC, shahargl commented
@mohanish2504 can you add `incidentmanager-provider.mdx` to mint.json so it will show up? also, can you add the logo to the README? I'll merge after.

2024-04-03 11:17 UTC, shahargl requested changes
see comments

2024-04-08 07:08 UTC, mohanish2504 commented
Hey @shahargl been busy since last few days, will try to push the commit by thursday at max.

2024-04-15 13:22 UTC, mohanish2504 commented
@shahargl can you have a look.

Also hope you guys are doing well.

2024-04-25 17:34 UTC, shahargl commented
@mohanish2504 yo - is this still relevant?

2024-04-25 18:12 UTC, mohanish2504 commented
any more changes required here? I have pushed the changes you left for review last time. Let me know if you want any other change.

I just saw the conflicts will resolve those too.

2024-04-25 18:46 UTC, shahargl commented on docs/mint.json
> +            "providers/documentation/zenduty-provider",
?

2024-04-25 18:46 UTC, shahargl commented on docs/mint.json
> +            "providers/documentation/resend-provider",
?

2024-04-25 18:47 UTC, shahargl commented
can you just fix the mint.json and remove the redundant logo? (only the -icon is needed)

2024-04-26 14:41 UTC, mohanish2504 commented
> t logo? (only the -icon is needed)

do you mean to also remove this?
`"providers/documentation/incidentmanager-provider"`

2024-04-26 15:26 UTC, shahargl commented
lgtm, merging @mohanish2504

2024-04-26 15:27 UTC, merged